#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

if [[ -f /etc/profile ]]; then
  source /etc/profile
fi

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
  export LC_COLLATE=C
  export LC_NUMERIC=C
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
  ~/.cargo/bin
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

fpath=(
    ~/.zfunc
    $fpath[@]
)

export GPG_TTY=$(tty)
export COPYFILE_DISABLE=1 # prevent tar from adding ._* files

if (( $+commands[ledger] || $+commands[hledger] )); then
    export LEDGER_PATH="$HOME/journal"
    export LEDGER_FILE=$LEDGER_PATH/journal.ldg
    export LEDGER_PRICE_DB=$LEDGER_PATH/pricedb.ldg
    export LEDGER_EXPLICIT=1
    export LEDGER_STRICT=1
    export LEDGER_DATE_FORMAT=%Y-%m-%d
fi

# Perl local::lib configuration
eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"

# rbenv
if (( $+commands[rbenv] )); then
    eval "$(rbenv init -)"
fi

export RIPGREP_CONFIG_PATH=~/.ripgreprc

export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'

export FZF_DEFAULT_OPTS='
  --color fg:-1,bg:-1,hl:33,fg+:254,bg+:235,hl+:33
  --color info:136,prompt:136,pointer:230,marker:230,spinner:136
'

if (( $+commands[patdiff-git-wrapper] )); then
    export GIT_EXTERNAL_DIFF=patdiff-git-wrapper
fi

path=(
    ~/bin
    $path
)

zprofile_sourced=1
