#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

if [[ -f /etc/profile ]]; then
  source /etc/profile
fi

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='emacsclient -a=vim'
export VISUAL='emacsclient -a=vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
  export LC_COLLATE=C
  export LC_NUMERIC=C
fi

#
# Paths
#

typeset -T INFOPATH infopath

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath infopath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /opt/homebrew/{bin,sbin}
  /usr/local/{bin,sbin}
  $path
  ~/.cargo/bin
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
export LESS='-g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

fpath=(
    ~/.zfunc
    $fpath
)

# Disable Homebrew phoning home
export HOMEBREW_NO_ANALYTICS=1

export GPG_TTY=$(tty)
export COPYFILE_DISABLE=1 # prevent tar from adding ._* files

export RIPGREP_CONFIG_PATH=~/.ripgreprc

export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'

export FZF_DEFAULT_OPTS='
  --color fg:-1,bg:-1,hl:33,fg+:254,bg+:235,hl+:33
  --color info:136,prompt:136,pointer:230,marker:230,spinner:136
'

export RSYNC_PROTECT_ARGS=1

if (( $+commands[patdiff-git-wrapper] )); then
    export GIT_EXTERNAL_DIFF=patdiff-git-wrapper
fi

path=(
    ~/bin
    $path
)

zprofile_sourced=1
