if [[ -z "$zprofile_sourced" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

COMPLETION_WAITING_DOTS="true"
PURE_GIT_PULL=0

alias db='danbooru-tool'
alias hs='python3 -m http.server'
if (( $+commands[vim] )); then
  alias vi='vim'
fi

alias mkdir="${aliases[mkdir]:-mkdir} -v"

# tmux aliases

alias ta='tmux attach -t'
alias tad='tmux attach -d -t'
alias ts='tmux new-session -s'
alias tl='tmux list-sessions'
alias tksv='tmux kill-server'
alias tkss='tmux kill-session -t'

# zmv aliases

alias zmv='noglob zmv'
alias zcp='noglob zmv -C'
alias zln='noglob zmv -L'

# Add sigils to ls output

alias ls="${aliases[ls]:-ls} -F"

# Allow interactive comments

setopt interactivecomments

if (( $+commands[direnv] )); then
  eval "$(direnv hook zsh)"
else
  echo "direnv not installed... ignoring."
fi

for profile in ''${(z)NIX_PROFILES}; do
  fpath=(
    $profile/share/zsh/site-functions
    $profile/share/zsh/$ZSH_VERSION/functions
    $profile/share/zsh/vendor-completions
    $fpath
  )
  infopath+=($profile/share/info)
  if [ -f $profile/share/bash-completion/completions/wl.bash ]; then
    source $profile/share/bash-completion/completions/wl.bash
  fi
done
