if [[ -z "$zprofile_sourced" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprofile"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

DEFAULT_USER="rouka"
COMPLETION_WAITING_DOTS="true"

alias e='open -a /Applications/Emacs.app'
alias db='danbooru-tool'
alias mplayer='mpv'
if is_installed vim; then
    alias vi='vim'
fi

# Use .env files for private environment variables

autoload -Uz source_env
source_env
autoload -U add-zsh-hook
add-zsh-hook chpwd source_env

# tmux aliases

alias ta='tmux attach -t'
alias tad='tmux attach -d -t'
alias ts='tmux new-session -s'
alias tl='tmux list-sessions'
alias tksv='tmux kill-server'
alias tkss='tmux kill-session -t'

# Add sigils to ls output

alias ls="${aliases[ls]:-ls} -F"

# Allow interactive comments

setopt interactivecomments
